### PR TITLE
Updated to Preview 6

### PR DESCRIPTION
**Pull request by MrNeta**
Changed return type of Remove methods

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
You could add SetEntitySyncedData and getEntitySyncedData

**Comment by FabianTerhorst** [comment]
and the signatures from the data methods changed in general, Get is now always an out var with an bool return

**Comment by MrNeta** [comment]
Ich werde das nach der Arbeit hinzufügen

**Comment by vadz1999** [comment]
dm me, or comment here when it'll be ready to merge

**Comment by MrNeta** [comment]
@FabianTerhorst did i forgot anything?

**Comment by FabianTerhorst** [comment]
For preview 6 it looks good.

**Comment by vadz1999** [comment]
can you update this for new file structure pls

**Pull request closed without merging**
