### PR TITLE
fixed horizontal scrolling

### PR DESCRIPTION
**Pull request by DasChaosAT**

### CODE REVIEW

**Comment by DasChaosAT** [comment]
And added missing Events

**Comment by FabianTerhorst** [comment]
I don't like that wrapping to prevent horizontal scrolling.

**Comment by DasChaosAT** [comment]
Me too, but it was requestet by vadzz

**Comment by FabianTerhorst** [comment]
But not when it makes the code unreadable.

**Comment by DasChaosAT** [comment]
Vadzz: "guys, who are writing c# examples, please split long lines
to avoid horizontal scroll"

If he says I should remove it, I will do that

**Comment by FabianTerhorst** [comment]
Can be merged.

**Comment by FabianTerhorst** [comment]
It looks better on the docs then in github

**Pull request merged**
